name: Set Supply Co
favicon: null
layout_spectrum: 0.747908754972741
typography_spectrum: 0.6358624869026244
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5632167621515691
  lightness: 0.7052629804238677
  saturation: 0.014928302261978388
  rhythmicContrast: 0.2574541852809489
purpose: []
